### ISSUE TITLE
unloadDevices atexit causes local test cleanup failures (at least on mac)

### ISSUE THREAD

**Issue by tlambert03** [tlambert03/pymmcore-plus#52]
Hey @ianhi, looks like #47 is causing some issues for napari-micromanager's tests (at least on mac, might be os-specific, but both @fdrgsp  and I see it now).    All tests pass, and then on text cleanup you get the following traceback unless you comment out the new 
```py
            atexit.register(
                api.Proxy(f"PYRO:{server.CORE_NAME}@{host}:{port}").unloadAllDevices
            )
```
 
```py
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/Users/talley/miniconda3/envs/napdev/lib/python3.9/site-packages/Pyro5/client.py", line 476, in __call__
    return self.__send(self.__name, args, kwargs)
  File "/Users/talley/miniconda3/envs/napdev/lib/python3.9/site-packages/Pyro5/client.py", line 224, in _pyroInvoke
    msg = protocol.recv_stub(self._pyroConnection, [protocol.MSG_RESULT])
  File "/Users/talley/miniconda3/envs/napdev/lib/python3.9/site-packages/Pyro5/protocol.py", line 189, in recv_stub
    header = connection.recv(6)  # 'PYRO' + 2 bytes protocol version
  File "/Users/talley/miniconda3/envs/napdev/lib/python3.9/site-packages/Pyro5/socketutil.py", line 435, in recv
    return receive_data(self.sock, size)
  File "/Users/talley/miniconda3/envs/napdev/lib/python3.9/site-packages/Pyro5/socketutil.py", line 159, in receive_data
    raise err
Pyro5.errors.ConnectionClosedError: receiving: not enough data
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/Users/talley/miniconda3/envs/napdev/lib/python3.9/site-packages/Pyro5/client.py", line 476, in __call__
    return self.__send(self.__name, args, kwargs)
  File "/Users/talley/miniconda3/envs/napdev/lib/python3.9/site-packages/Pyro5/client.py", line 224, in _pyroInvoke
    msg = protocol.recv_stub(self._pyroConnection, [protocol.MSG_RESULT])
  File "/Users/talley/miniconda3/envs/napdev/lib/python3.9/site-packages/Pyro5/protocol.py", line 189, in recv_stub
    header = connection.recv(6)  # 'PYRO' + 2 bytes protocol version
  File "/Users/talley/miniconda3/envs/napdev/lib/python3.9/site-packages/Pyro5/socketutil.py", line 435, in recv
    return receive_data(self.sock, size)
  File "/Users/talley/miniconda3/envs/napdev/lib/python3.9/site-packages/Pyro5/socketutil.py", line 159, in receive_data
    raise err
Pyro5.errors.ConnectionClosedError: receiving: not enough data
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/Users/talley/miniconda3/envs/napdev/lib/python3.9/site-packages/Pyro5/socketutil.py", line 151, in receive_data
    chunk = sock.recv(min(60000, size - msglen))
ConnectionResetError: [Errno 54] Connection reset by peer
```

it _might_ be an issue that you're registering a bound method of a proxy (rather than a function that tries to create a proxy and then tries to call a method)... but I'm not sure yet

**Comment by ianhi** [comment]
oh hmm. it also is happening on the windows tests see: https://github.com/tlambert03/napari-micromanager/runs/3535568029?check_suite_focus=true but not on this repos tests. I wonder if this is something like the viewer fixture is constantly opening new servers that end up with different ports but we only kill the default ports.
